mode: distance
dataset_name: VOC
device: 0
plots: false
ranges: [0.05, 0.075, 0.1, 0.125, 0.15, 0.175, 0.2]
bg2all_ratio: 0
prepare_script: prepare_al_split.py
weights_base_path: /home/setupishe/ultralytics/runs/detect
weights_template: "${weights_base_path}/VOC_${folder_name}_${range}_s_5_20_night_pseudo/weights/best.pt"
first_weights_template: "${weights_base_path}/VOC_random_${range}_s_5_20_night/weights/best.pt"
split_name: distance_s_5_20_night_pseudo

prepare_args:
  seg2line: true
  cleanup: true
  from_predictions: true

yolo_args:
  model: yolov8s.pt
  pretrained: "False"
  data: "VOC_${next_range}_${split_name}.yaml"
  batch: 48
  name: "VOC_distance_${next_range}_s_5_20_night_pseudo"
  device: "${device}"
  epochs: 65
  deterministic: "True"
