mode: distance
dataset_name: VOC
device: 0
ranges: [0.2, 0.3, 0.4, 0.5, 0.6]
bg2all_ratio: 0
prepare_script: prepare_al_split.py
weights_base_path: /home/setupishe/ultralytics/runs/detect
split_name: temp
tune: true

prepare_args:
  seg2line: true
  cleanup: true

yolo_args:
  model: yolov8s.pt
  pretrained: "False"
  data: "${DATASET_NAME}_${next_range}_${mode}.yaml"
  batch: 48
  name: "${DATASET_NAME}_${mode}_${next_range}"
  device: "${device}"
  epochs: 30
