mode: distance
dataset_name: VOC
device: 0
plots: false
ranges: [0.2, 0.3]
bg2all_ratio: 0
prepare_script: prepare_al_split.py
weights_base_path: /home/setupishe/ultralytics/runs/detect
first_weights_template: "${weights_base_path}/VOC_random_${range}_s_scratch/weights/best.pt"
weights_template: "${weights_base_path}/VOC_distance_${range}_s_scratch_v3_rand_subset/weights/best.pt"
split_name: distance_s_scratch_v3_rand_subset
time: true

prepare_args:
  seg2line: false
  cleanup: true
  batched_inference: false
  index_backend: annoy
  roi_hw: [12, 6]
  netron_layer_names: "/model.22/Concat /model.22/Concat_1 /model.22/Concat_2"
  # skip_pca absent -> PCA enabled
  # coarse_to_fine absent -> plain Annoy

yolo_args:
  model: yolov8s.yaml
  pretrained: "False"
  data: "VOC_${next_range}_${split_name}.yaml"
  imgsz: 640
  batch: 48
  epochs: 65
  seed: 0
  name: "VOC_distance_${next_range}_s_scratch_v3_rand_subset"
  device: "${device}"
