mode: distance
dataset_name: VOC
device: 0
ranges: [0.2, 0.3, 0.4, 0.5, 0.6]
bg2all_ratio: 0
prepare_script: prepare_al_split.py
weights_base_path: src/ultralytics/runs/detect
split_name: distance

prepare_args:
  seg2line: true
  cleanup: true

yolo_args:
  model: yolov8m.pt
  pretrained: "False"
  data: "${DATASET_NAME}_${next_range}_${split_name}.yaml"
  batch: 48
  name: "${DATASET_NAME}_${mode}_${next_range}"
  device: "${device}"
  epochs: 65
