bg2all_ratio: 0
dataset_name: VOC
device: 0
first_weights_template: ${weights_base_path}/VOC_random_${range}_s_matryoshka_everything_really_everything_5_20/weights/best.pt
mode: distance
prepare_args:
  cleanup: false
  from_predictions: true
  image_aggregation: sum
  index_backend: hnsw
  io_workers: 4
  netron_layer_names: /model.15/cv2/act/Mul /model.18/cv2/act/Mul /model.21/cv2/act/Mul
  onnx_batch_size: 16
  roi_hw:
  - 4
  - 4
  seg2line: true
  skip_pca: true
prepare_script: prepare_al_split.py
ranges:
- 0.05
- 0.075
- 0.1
- 0.125
- 0.15
- 0.175
- 0.2
split_name: distance_matr_sum_s_5_20
weights_base_path: /home/setupishe/ultralytics/runs/detect
weights_template: ${weights_base_path}/VOC_${folder_name}_${range}_s_matr_sum_5_20/weights/best.pt
yolo_args:
  batch: 48
  data: VOC_${next_range}_${split_name}.yaml
  device: ${device}
  epochs: 65
  deterministic: "True"
  matryoshka: 'True'
  matryoshka_bn_aux_freeze: 'true'
  matryoshka_shared_assign: 'true'
  matryoshka_weight_warmup: 'true'
  matryoshka_weight_warmup_start_step: 10
  matryoshka_weight_warmup_steps: 20
  model: yolov8s.pt
  name: VOC_distance_${next_range}_s_matr_sum_5_20
  pretrained: 'False'
