type: random_train
fractions: [0.05, 0.075, 0.1, 0.125, 0.15, 0.175, 0.2]

yolo_args:
  data: "VOC_${fraction}.yaml"
  model: yolov8s.pt
  imgsz: 640
  batch: 48
  epochs: 65
  pretrained: "False"
  seed: 0
  deterministic: "False"
  name: "VOC_random_${fraction}_s_5_20_night"
